In [11]:
import tensorflow as tf
import numpy as np

tfs = tf.InteractiveSession()
hello = tf.constant("Hello Tensorflow")
print(tfs.run(hello))

b'Hello Tensorflow'


/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [3]:
c1 = tf.constant(5, name='x')
c2 = tf.constant(6.0, name='y')
c3 = tf.constant(7.0, tf.float32, name='z')

print('c1 (x): ', c1)
print('c2 (y): ', c2)
print('c3 (z): ', c3)

print('run([c1, c2, c3]) : ', tfs.run([c1, c2, c3]))

c1 (x):  Tensor("x_1:0", shape=(), dtype=int32)
c2 (y):  Tensor("y_1:0", shape=(), dtype=float32)
c3 (z):  Tensor("z_1:0", shape=(), dtype=float32)
run([c1, c2, c3]) :  [5, 6.0, 7.0]


In [4]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)

result1 = tfs.run(op1)
result2 = tfs.run(op2)

print(result1)
print(result2)

13.0
42.0


In [6]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1: ', p1)
print('p2: ', p2)

op4 = p1 * p2
result_placeholders = tfs.run(op4, {p1: 2.0, p2: 3.0})

print(result_placeholders)

p1:  Tensor("Placeholder_6:0", dtype=float32)
p2:  Tensor("Placeholder_7:0", dtype=float32)
6.0


In [7]:
result_placeholders_vector = tfs.run(op4, feed_dict={p1: [2.0, 3.0, 4.0], p2: [3.0, 4.0, 5.0]})
print(result_placeholders_vector)

[ 6. 12. 20.]


In [9]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print(tf_t)
print(tfs.run(tf_t))

Tensor("Const_2:0", shape=(), dtype=float64)
5.0


In [13]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print(a1dim)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print(tf_t)
print(tf_t[0])
print(tf_t[2])
print(tfs.run(tf_t))

[1.   2.   3.   4.   5.99]
Tensor("Const_5:0", shape=(5,), dtype=float64)
Tensor("strided_slice_2:0", shape=(), dtype=float64)
Tensor("strided_slice_3:0", shape=(), dtype=float64)
[1.   2.   3.   4.   5.99]


In [15]:
a2dim = np.array([
    (1, 2, 3, 4, 5.99),
    (2, 3, 4, 5, 6.99),
    (3, 4, 5, 6, 7.99)
])
print(a2dim.shape)
tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)
print(tfs.run(tf_t))

(3, 5)
[[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


In [19]:
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x = tf.placeholder(tf.float32)
y = w * x + b

print(w)
print(x)
print(b)
print(y)
tfs.run(tf.global_variables_initializer())
print('run(y, {x:[1, 2, 3, 4]} : ', tfs.run(y, {x: [1, 2, 3, 4]}))

<tf.Variable 'Variable_6:0' shape=(1,) dtype=float32_ref>
Tensor("Placeholder_11:0", dtype=float32)
<tf.Variable 'Variable_7:0' shape=(1,) dtype=float32_ref>
Tensor("add_3:0", dtype=float32)
run(y, {x:[1, 2, 3, 4]} :  [0.         0.3        0.6        0.90000004]
